name: file-size-check
on: [pull_request]
jobs:
  file-size-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set target files
        run: sh file_size_check.sh

      - name: Add pull request about file size
        uses: actions/github-script@0.3.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: file_size_check.js
          # script: |
          #   const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
          #   github.issues.createComment({ issue_number, owner, repo, body: 'large size file exist: ${{ sh file_size_check.sh }}'' });
