name: file-size-check
on:
  pull_request:
    types: [opened, reopened]
jobs:
  check-file-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: find ./public/ -size +5k
      - run: echo 'File Size Check'
